Repository 3sam5oh/webtoon-search-service, pull requests merged in 2024-07, with the labels that each got.

#33 [chore] 자바 버전 업데이트
  .gitignore
  webtoon-search-back/webtoon-search/.github/pull_request_template.md
  webtoon-search-back/webtoon-search/.gitignore
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/src/main/resources/application.yml
Labels: documentation, good first issue

#37 Feature/backend project structure
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/in/rest/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/in/rest/dto/WebtoonSearchResponseDTO.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/out/opensearch/OpenSearchWebtoonRepository.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/out/persistence/JpaUserRepository.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/domain/SearchableWebtoon.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SearchWebtoonUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/LoadWebtoonPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/config/OpenSearchConfig.java
Labels: enhancement

#60 [feat] 프로젝트 구조 개선 후 검색 기능 구현
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/WebtoonSearchApplication.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/config/SearchEngineConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/in/rest/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/in/rest/dto/WebtoonSearchResponseDTO.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/out/opensearch/OpenSearchWebtoonRepository.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/out/persistence/JpaUserRepository.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/SearchPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/SearchWebtoonEntity.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/searchengine/SearchEngineAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/domain/SearchableWebtoon.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SearchWebtoonCommand.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SearchWebtoonUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/WebtoonResult.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/LoadWebtoonPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/LoadWebtoonQuery.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/ApiResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/GlobalExceptionHandler.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/config/OpenSearchConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/domain/SearchableWebtoon.java
Labels: enhancement, refactor

#62 [chore] 로컬환경에서 OpenSearch dashboards에 없는 plug-in 설치 명령어 추가
  webtoon-search-back/webtoon-search/Dockerfile
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
Labels: enhancement

#84 [chore] OpenSearch Docker 환경 설정 및 초기화 스크립트 개선
  webtoon-search-back/webtoon-search/.gitattributes
  webtoon-search-back/webtoon-search/Dockerfile
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
  webtoon-search-back/webtoon-search/docker/Dockerfile
  webtoon-search-back/webtoon-search/init/init-opensearch.sh
  webtoon-search-back/webtoon-search/init/setup-opensearch.sh
  webtoon-search-back/webtoon-search/init/webtoon-mapping.json
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/SearchWebtoonEntity.java
Labels: enhancement, refactor

#63 [feat] springboot project 사용자 정의 메트릭 추가
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/WebtoonSearchApplication.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/searchengine/SearchEngineAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/GlobalExceptionHandler.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/metrics/CustomMetrics.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/metrics/config/MetricsConfig.java
Labels: enhancement, help wanted

#88 [chore] OpenSearch Docker 환경 설정 이슈 해결
  webtoon-search-back/webtoon-search/.editorconfig
  webtoon-search-back/webtoon-search/.gitattributes
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
  webtoon-search-back/webtoon-search/docker/Dockerfile
  webtoon-search-back/webtoon-search/init/init-opensearch.sh
  webtoon-search-back/webtoon-search/init/setup-opensearch.sh
Labels: bug, refactor

#90 [feat] OAuth를 활용한 로그인 기능 구현
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/config/SecurityConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/UserEntity.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/UserPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/UserRepository.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/OAuthController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/OAuthResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/RegisterUserCommand.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/RegisterUserUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/SaveUserPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/UserService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/domain/User.java
  webtoon-search-front/.gitignore
  webtoon-search-front/.vscode/extensions.json
  webtoon-search-front/README.md
  webtoon-search-front/babel.config.js
  webtoon-search-front/index.html
  webtoon-search-front/jsconfig.json
  webtoon-search-front/package-lock.json
  webtoon-search-front/package.json
  webtoon-search-front/public/index.html
  webtoon-search-front/src/App.vue
  webtoon-search-front/src/assets/base.css
  webtoon-search-front/src/assets/logo.png
  webtoon-search-front/src/assets/logo.svg
  webtoon-search-front/src/assets/main.css
  webtoon-search-front/src/components/HelloWorld.vue
  webtoon-search-front/src/components/TheWelcome.vue
  webtoon-search-front/src/components/WelcomeItem.vue
  webtoon-search-front/src/components/icons/IconCommunity.vue
  webtoon-search-front/src/components/icons/IconDocumentation.vue
  webtoon-search-front/src/components/icons/IconEcosystem.vue
  webtoon-search-front/src/components/icons/IconSupport.vue
  webtoon-search-front/src/components/icons/IconTooling.vue
  webtoon-search-front/src/main.js
  webtoon-search-front/src/router/index.js
  webtoon-search-front/src/views/CallbackView.vue
  webtoon-search-front/src/views/Home.vue
  webtoon-search-front/vite.config.js
  webtoon-search-front/vue.config.js
Labels: enhancement

#91 [feat] Spring boot active/error logging 관련 기능 추가
  webtoon-search-back/webtoon-search/Dockerfile
  webtoon-search-back/webtoon-search/Dockerfile-spring
  webtoon-search-back/webtoon-search/build.gradle
  webtoon-search-back/webtoon-search/gradle.properties
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/SelectPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/SelectRecordEntity.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/rdbms/SelectRecordAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SelectRecordController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/SelectRecordRequest.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SelectRecordUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SelectWebtoonDTO.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/AddRecordPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SelectRecordService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/logs/LoggingAspect.java
  webtoon-search-back/webtoon-search/src/main/resources/log4j2-spring.xml
Labels: enhancement, help wanted

#92 [test][chore] 단위 테스트 추가 및 Text file line endings 설정
  webtoon-search-back/webtoon-search/.gitattributes
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
  webtoon-search-back/webtoon-search/docker/Dockerfile
  webtoon-search-back/webtoon-search/init/init-opensearch.sh
  webtoon-search-back/webtoon-search/init/setup-opensearch.sh
  webtoon-search-back/webtoon-search/src/test/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonControllerUnitTest.java
  webtoon-search-back/webtoon-search/src/test/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonServiceUnitTest.java
  webtoon-search-back/webtoon-search/src/test/java/com/samsamohoh/webtoonsearch/domain/SearchableWebtoonUnitTest.java
Labels: enhancement, help wanted

#95 [refactor] 프로젝트 구조 개선 및 Docker 설정 최적화
  webtoon-search-back/webtoon-search/Dockerfile
  webtoon-search-back/webtoon-search/docker-compose.dev.yml
  webtoon-search-back/webtoon-search/docker/Dockerfile-opensearch
  webtoon-search-back/webtoon-search/docker/Dockerfile-spring
  webtoon-search-back/webtoon-search/gradle.properties
  webtoon-search-back/webtoon-search/opensearch-init/init-opensearch.sh
  webtoon-search-back/webtoon-search/opensearch-init/setup-opensearch.sh
  webtoon-search-back/webtoon-search/opensearch-init/webtoon-mapping.json
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/config/SecurityConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/MemberPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/RegisterMemberEntity.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/UserPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/rdbms/MemberPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/rdbms/SelectRecordAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/searchengine/SearchEngineAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/OAuthController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/member/OAuthController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/member/OAuthResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/webtoon/SearchWebtoonController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/webtoon/SearchWebtoonResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/webtoon/SelectRecordController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/webtoon/SelectRecordRequest.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/RegisterUserUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/SelectRecordUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/member/RegisterMemberCommand.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/member/RegisterMemberUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/LoadWebtoonQuery.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/SearchWebtoonCommand.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/SearchWebtoonUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/SelectRecordUseCase.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/SelectWebtoonDTO.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/webtoon/WebtoonResult.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/AddRecordPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/LoadWebtoonPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/SaveMemberPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/SaveUserPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/RegisterMemberService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/SelectRecordService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/UserService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/GlobalExceptionHandler.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/logs/LoggingAspect.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/common/metrics/config/MetricsConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/domain/MemberValidation.java
  webtoon-search-back/webtoon-search/src/test/java/com/samsamohoh/webtoonsearch/adapter/web/SearchWebtoonControllerUnitTest.java
  webtoon-search-back/webtoon-search/src/test/java/com/samsamohoh/webtoonsearch/application/service/SearchWebtoonServiceUnitTest.java
Labels: refactor

#104 [feat][chore] Dockerfile 및 GitHub Actions 워크플로우 최적화
  webtoon-search-back/webtoon-search/.github/workflows/jar-image-push.yml
  webtoon-search-back/webtoon-search/docker/Dockerfile-spring
Labels: enhancement

#105 [refactor] 로그인 기능 프로젝트 구조 개선
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/config/SecurityConfig.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/persistence/RegisterMemberEntity.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/rdbms/MemberPersistenceAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/rdbms/MemberRecordAdapter.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/member/OAuthController.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/adapter/web/member/OAuthResponse.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/in/member/RegisterMemberCommand.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/port/out/SaveMemberPort.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/application/service/RegisterMemberService.java
  webtoon-search-back/webtoon-search/src/main/java/com/samsamohoh/webtoonsearch/domain/MemberValidation.java
Labels: refactor
